package io.github.isuzuki.openrtb2_5.request

trait Device {
  val ua:             Option[String]
  val geo:            Option[Geo]
  val dnt:            Option[Int]
  val lmt:            Option[Int]
  val ip:             Option[String]
  val ipv6:           Option[String]
  val devicetype:     Option[Int]
  val make:           Option[String]
  val model:          Option[String]
  val os:             Option[String]
  val osv:            Option[String]
  val hwv:            Option[String]
  val h:              Option[Int]
  val w:              Option[Int]
  val ppi:            Option[Int]
  val pxratio:        Option[Float]
  val js:             Option[Int]
  val geofetch:       Option[Int]
  val flashver:       Option[String]
  val language:       Option[String]
  val carrier:        Option[String]
  val mccmnc:         Option[String]
  val connectiontype: Option[Int]
  val ifa:            Option[String]
  val didsha1:        Option[String]
  val didmd5:         Option[String]
  val dpidsha1:       Option[String]
  val dpidmd5:        Option[String]
  val macsha1:        Option[String]
  val macmd5:         Option[String]
  val ext:            Option[Ext]
}
